### ISSUE TITLE
Wrong icon in task switcher (alt+tab) under KDE Plasma Wayland session

### ISSUE THREAD

**Issue by glaubersm** [flathub/com.github.wwmm.pulseeffects#19]
start KDE Plasma Wayland sesison
open any window
install pulseeffects from flathub
open pulseeffects
press alt+tab: the task switcher shows Wayland generic icon instead correct pulseeffects icon.

My system:
Arch Linux
pulseeffects 4.3.4
KDE Plasma 5.14 (Wayland session)
flatpak 1.0.4

**Comment by glaubersm** [comment]
pulseeffects icon in the task switcher is also wrong under X11.
What do you think?

**Comment by AsavarTzeth** [comment]
I did experience this (or something similar) randomly, but rarely, in the past but have not had any issues for a very long time.

Is this still an issue?

**Comment by glaubersm** [comment]
This issue is still valid.

Arch Linux
pulseeffects 4.6.5
KDE Plasma 5.16.3 (Wayland session)
flatpak 1.4.2

**Comment by V0ldemrt** [comment]
I can confirm it works on kubuntu 20.04 LTS fresh install with custom Candy icons

**Comment by vchernin** [comment]
It's been a while, but could you test the Flatpak build of EasyEffects (succesor to PulseEffects, PipeWire-only).
I can't reproduce this issue on my KDE Arch Wayland VM with the Flatpak build.
https://github.com/flathub/flathub/pull/2429

If you notice the EasyEffects icon is there, but has a black square in the bottom right see https://github.com/wwmm/easyeffects/issues/867

**Comment by glaubersm** [comment]
Tested flatpak build on Arch right now. Easyeffects has no icon in upper left corner and in alt+menu.

**Comment by wwmm** [comment]
>Tested flatpak build on Arch right now. Easyeffects has no icon in upper left corner and in alt+menu.

The icon problem is known. And the solution will probably involve having to embed these icons in our executable. Not all of the icons in the Adwaita icon theme have an alternative in other icons themes.

**Comment by glaubersm** [comment]
After reboot alt+tab displays easyeffects icon, but still no icon in the upper left corner.

![icon](https://user-images.githubusercontent.com/15967631/129791612-fb937b4a-4205-492e-93f3-3bafbce2bade.png)

**Comment by wwmm** [comment]
>but still no icon in the upper left corner.

I imagine that this icon is related to the gtk integration in non gtk desktops. Our window is not supposed to have an icon in this location
![Screenshot from 2021-08-17 16-58-44](https://user-images.githubusercontent.com/16225172/129792119-709f866f-d4a6-49d9-87ef-6dae9b9fbcdd.png)

**Comment by wwmm** [comment]
On a side note I have to remember spend some time someday to update the pt_BR translations... But translating is so time consuming... And boring...

**Comment by vchernin** [comment]
I found theming on on KDE whether Flatpak or not to be quite inconsistent. However the broken top left icon on KDE is a Flatpak related issue.

The Arch package shows the top left icon succesfully on KDE, but the Flatpak does it broken like above.

Arch package:
![image](https://user-images.githubusercontent.com/38842733/129805245-b3edc412-24ad-4f80-abcc-f1fd4a95200d.png)

This is almost certainly the same cause as the about page originally having a broken icon. Flatpak expects icons to be named `com.github.wwmm.easyeffects`, and deviating from that causes problems. 

I could add a Flatpak patch the top left icon to make it display properly, but since it's not supposed to show up in the first place I'm not sure. One day I'd like to learn how Flatpak and non Flatpak apps are supposed to get along in terms of icons.

**Comment by vchernin** [comment]
This issue should have been fixed, since I just decided to leave the icon under both names.
